#!/bin/sh

. /etc/init.d/functions

do_start() {
	/usr/local/bin/coffeeplace -platform eglfs &
}

do_stop() {
	killproc coffeeplace
}

case "$1" in
  start)
	echo "Starting coffeeplace app"
	do_start
	;;
  stop)
	echo "Stopping coffeeplace app"
	do_stop
	;;
  restart|force-reload)
	echo "Restarting coffeeplace app"
	do_stop
	sleep 1
	do_start
	;;
  *)
	echo "Usage: $0 {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0
